namespace Paradox.Networking;

public enum ParadoxRpcId : uint
{
    HandshakeHello = 0,
    SyncParadoxMeter = 1,
    AssignRole = 2,
    UseRoleAbility = 3,
    SyncRoleState = 4,
    ObserverTrace = 5,
    ParasiteInfection = 6,
    SyncRoleSetting = 7,
    CleanerCleanBody = 8,
    TriggerParadoxFinalEvent = 9,
    DoppelgangerState = 10,
    AnomalyPulse = 11,
    GuardianProtect = 12,
    StabilizerPulse = 13,
    MedicScan = 14,
    TrackerTrack = 15,
    ForensicExamine = 16,
    DetectiveScan = 17,
    ChronologistReadTimeline = 18,
    AnalystScan = 19,
    NightmareHaunt = 20,
    SeerReadAura = 21,
    DevourerConsume = 22,
    RiftmakerWarp = 23,
    CorruptorCorrupt = 24,
    BountyHunterState = 25,
    HarbingerOmen = 26,
    CollectorSample = 27,
    EngineerXRepair = 28,
    DispatcherSweep = 29,
    LocksmithOpenDoor = 30,
    TechnicianShield = 31,
    SaboteurOverload = 32,
    UndertakerCarryBody = 33,
    TimebreakerStasis = 34,
    IllusionistMirage = 35,
    PuppeteerControl = 36,
    ShapeshifterXSwap = 37,
    ForgottenMemory = 38
}
